name = "moneten"
account_id = "8331328a071250c86d7b750636e3fa27"
compatibility_date = "2025-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "moneten"
database_id = "04e095cf-1d63-4fde-b655-7834fa91a004"
