name = "moneten"
compatibility_date = "2025-09-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "moneten"
database_id = "PLATZHALTER-NACH-WRANGLER-LOGIN-EINTRAGEN"
